### ISSUE TITLE
Show other notifications?

### ISSUE THREAD

**Issue by fourzerofour** [jgeboski/bitlbee-steam#62]
Hi! If these are possible at all, can we see notification messeges implemented for events such as new {comments, items in inventory, gifts, pending trade offer}? You already covered friends invites and offline messages

**Comment by jgeboski** [comment]
I am going to close this for now (over a year later).  This would require introducing more usage of the Steam Community API, which is already proving to be problematic elsewhere in the plugin.  And the plugin would need to poll another HTTP source, since such information is not sent over the main poll request.
